{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.dr460nixed;
in
{
  environment.systemPackages =
    let
      required-packages = with pkgs; [
        bind
        btop
        cached-nix-shell
        duf
        eza
        fishPlugins.sponge
        fishPlugins.plugin-sudope
        fishPlugins.plugin-git
        fishPlugins.done
        jq
        killall
        micro
        nettools
        python3
        tldr
        tmux
        traceroute
        tmuxPlugins.catppuccin
        ugrep
        wget
      ];
    in
    required-packages
    ++ lib.optionals cfg.yubikey.enable [
      pkgs.yubioath-flutter
    ]
    ++ lib.optionals cfg.live-cd.enable (
      with pkgs;
      [
        btrfs-progs
        chntpw
        cryptsetup
        dosfstools
        e2fsprogs
        efibootmgr
        flashrom
        gnutar
        gparted
        hexedit
        home-manager
        hwinfo
        inxi
        memtest86-efi
        ntfs3g
        nvme-cli
        p7zip
        pciutils
        perl
        qemu-utils
        rsync
        tcpdump
        testdisk
        util-linux
        wipe
        xfsprogs
      ]
    );
}
