{
  imports = [
    ./apps.nix
    ./boot.nix
    ./chaotic/chaotic.nix
    ./common.nix
    ./desktops.nix
    ./development.nix
    ./gaming.nix
    ./hardening.nix
    ./locales.nix
    ./misc.nix
    ./networking.nix
    ./performance.nix
    ./servers.nix
    ./shells.nix
    ./xdg-ninja
  ];
}
