[default]
extend-ignore-identifiers-re = [
  "crypted",
  "immortalis",
  "odf"
]

[type.css]
check-file = false

[type.secrets]
extend-glob = ["global.yaml"]
check-file = false

[type.changelog]
extend-glob = ["CHANGELOG.md"]
check-file = false
