{
  imports = [
    ../../overlays
    ./apps.nix
    ./boot.nix
    ./chaotic/chaotic.nix
    ./common.nix
    ./desktops.nix
    ./docker-compose-runner.nix
    ./deterministic-ids.nix
    ./development.nix
    ./gaming.nix
    ./hardening.nix
    ./locales.nix
    ./misc.nix
    ./monitoring.nix
    ./msmtp.nix
    ./networking.nix
    ./nix.nix
    ./oci.nix
    ./users.nix
    ./servers.nix
    ./shells.nix
    ./syncthing.nix
    ./tailscale.nix
    ./tailscale-tls.nix
    ./zfs.nix
  ];
}
