{
  imports = [
    ./apps.nix
    ./boot.nix
    ./common.nix
    ./desktops.nix
    ./docker-compose-runner.nix
    ./development.nix
    ./gaming.nix
    ./hardening.nix
    ./home-manager.nix
    ./locales.nix
    ./networking.nix
    ./nix.nix
    ./users.nix
    ./tailscale.nix
    ./tailscale-tls.nix
    ./zfs.nix
  ];
}
